.github/workflows/tests.yml
README.md
package.json

Create GitHub Action workflow: tests.yml

---

.github/workflows/codeql-analysis.yml

Set-up automatic code-analysis

---

.gitignore
.vscode/extensions.json
.vscode/settings.json
README.md

Include workspace configurations to be shared

---

client/src/app/models/role.enum.ts
client/src/app/models/topic.enum.ts
client/src/app/models/view-mode.enum.ts
client/src/app/services/state.service.spec.ts
client/src/app/services/state.service.ts

Add StateService with initial values/options

---

.github/workflows/azure-static-web-apps-orange-grass-0aefaa103.yml
client/package.json
client/staticwebapp.config.json

cd: Configure the development deployment Static WebApp

---

.github/workflows/azure-static-web-apps-orange-grass-0aefaa103.yml
client/package.json
package.json

ci: Try different config to use newer Node version

---

client/src/app/components/shared.module.ts
client/src/app/home/home.module.ts
client/src/app/pages/program/program.module.ts
client/src/app/pages/program/program.page.spec.ts
client/src/app/pages/program/program.page.ts

fix program page test

---

client/package.json
client/src/app/app.module.ts
client/src/app/components/shared.module.ts
client/src/app/components/sidebar/sidebar.component.html
client/src/app/components/sidebar/sidebar.component.scss
client/src/app/components/sidebar/sidebar.component.spec.ts
client/src/app/components/sidebar/sidebar.component.ts
client/src/app/pages/program/program.page.html
client/src/global.scss

Set up global app/page layout #54

---

client/src/app/app-routing.module.ts
client/src/app/home/home.page.html
client/src/app/pages/report/report-routing.module.ts
client/src/app/pages/report/report.module.ts
client/src/app/pages/report/report.page.html
client/src/app/pages/report/report.page.spec.ts
client/src/app/pages/report/report.page.ts
client/src/assets/i18n/en.json

#55 Add report page

---

client/angular.json
client/src/app/components/program-phase/program-phase.component.html
client/src/app/components/program-phase/program-phase.component.spec.ts
client/src/app/components/program-phase/program-phase.component.ts
client/src/app/components/shared.module.ts
client/src/app/home/home.page.html
client/src/app/pages/program/program-routing.module.ts
client/src/app/pages/program/program.page.html
client/src/app/pages/program/program.page.spec.ts
client/src/app/pages/report/report.page.html
client/src/app/pages/report/report.page.spec.ts
client/src/assets/i18n/en.json

#58 Add program phases component

---

client/src/app/components/question-section/question-section.component.spec.ts
client/src/app/mocks/program.mock.ts
client/src/app/services/state.service.spec.ts
client/src/app/services/state.service.ts
client/src/app/services/translatable-string.service.spec.ts
client/src/app/services/translatable-string.service.ts

Improve translatability of Section-properties

---

client/src/app/components/user-state/user-state.component.spec.ts
client/src/app/components/user-state/user-state.component.ts
client/src/app/models/user.model.ts
client/src/app/services/api.service.ts
client/src/app/services/auth.service.ts

fix: Use consistent spelling of UserName everywhere

---

client/src/app/components/nav-progress/nav-progress.component.html
client/src/app/components/nav-progress/nav-progress.component.spec.ts
client/src/app/components/nav-progress/nav-progress.component.ts
client/src/app/components/shared.module.ts
client/src/app/pages/program/program.page.html
client/src/app/services/state.service.ts
client/src/assets/i18n/en.json

112  create NavProgress component

---

.github/workflows/tests.yml
client/src/app/components/login-form/login-form.component.html
client/src/app/home/home.page.html
client/src/app/home/home.page.spec.ts
client/src/app/home/home.page.ts
server/package.json
server/src/main.ts
server/src/users/user.controller.ts
server/test/app.e2e-spec.ts

Misc test/login fixes

---

client/src/app/components/filters/filters.component.ts
client/src/app/services/state.service.ts

Make the StateService always contain 'something' for the sections

---

client/src/app/components/nav-progress/nav-progress.component.html
client/src/app/pages/program/program.page.html
client/src/app/services/program-data.service.ts
client/src/assets/i18n/en.json

Tweak NavProgress-component

---

README.md
data/.gitignore
server/src/scripts/scripts.controller.ts
server/src/scripts/seed-program-demo.ts
server/src/seed-data/narrativeReportTemplate-demo-en.ts
server/tsconfig.json

docs: Explain mock/seed-data structure + how-to for deployments

---

client/src/app/models/question-data.model.ts
client/src/app/services/program-data.service.ts

feat: only use unique Tag-values in interface

---

client/src/app/components/report-narrative/report-narrative.component.html
client/src/app/components/report-narrative/report-narrative.component.scss
client/src/app/components/report-narrative/report-narrative.component.spec.ts
client/src/app/components/report-narrative/report-narrative.component.ts
client/src/app/components/report-section/report-section.component.html
client/src/app/components/report-section/report-section.component.ts
client/src/app/components/shared.module.ts
client/src/app/mocks/program.mock.ts
client/src/app/pages/report/report-helpers.ts
client/src/app/pages/report/report.page.html
client/src/app/services/program-data.service.ts
client/src/app/services/state.service.ts
client/src/app/types/program.type.ts
client/src/app/types/question-section.type.ts
client/src/assets/i18n/en.json

Show answers in narrative report text

---

client/src/app/components/filters/filters.component.html
client/src/app/components/nav-progress/nav-progress.component.html
client/src/app/components/program-phase/program-phase.component.html
client/src/app/components/question-section/question-section.component.html
client/src/app/pages/program/program.page.html
client/src/app/pages/report/report.page.html
client/src/global.scss

Tweak layout to be more mobile-friendly

---

client/src/app/components/nav-progress/nav-progress.component.html
client/src/app/components/question-section/question-section.component.html
client/src/app/components/question-section/question-section.component.spec.ts
client/src/app/components/question-section/question-section.component.ts
client/src/app/services/program-data.service.ts
client/src/global.scss

Automatically save input

---

client/src/app/components/filters/filters.component.html
client/src/app/components/filters/filters.component.ts
client/src/app/components/question-section/question-section.component.html
client/src/app/components/question-section/question-section.component.ts
client/src/app/home/home.page.html
client/src/app/home/home.page.spec.ts
client/src/app/home/home.page.ts
client/src/app/models/tag.enum.ts
client/src/app/pages/program/program.page.ts
client/src/app/services/state.service.ts
client/src/assets/i18n/en.json

Hide questions based on Tag-filter

---

client/src/app/components/report-narrative/report-narrative.component.ts
client/src/app/mocks/program.mock.ts

Add mock/test data for "multiple output of single variable" in Report

---

client/package-lock.json
client/package.json
client/src/app/components/report-narrative/report-narrative.component.html
client/src/app/components/report-narrative/report-narrative.component.ts
client/src/assets/i18n/en.json

Add "Copy to Clipboard"-action to Report

---

server/src/users/dto/assign-user.dto.ts
server/src/users/user.service.ts

fix: Search for the actual user that is logging-in, instead of the first

---

client/src/app/components/filters/filters.component.ts

fix: Tag translations disappearing on page refresh

---

client/src/app/components/question-section/question-section.component.html
client/src/app/components/question-section/question-section.component.ts
client/src/app/components/user-state/user-state.component.spec.ts
client/src/app/mocks/mock-helpers.ts
client/src/app/mocks/program.mock.ts
client/src/app/models/user.model.ts
client/src/app/models/view-mode.enum.ts
client/src/app/services/auth.guard.ts
client/src/app/services/auth.service.ts
client/src/app/services/state.service.spec.ts
client/src/app/services/state.service.ts
client/src/global.scss
server/src/auth/roles-program.guard.ts
server/src/auth/roles.guard.ts
server/src/types/user-token.type.ts
server/src/users/user.decorator.ts
server/src/users/user.service.ts

Enable switch between edit/read-only based on logged-in user

---

client/src/app/components/connection-status/connection-status.component.html
client/src/app/components/connection-status/connection-status.component.spec.ts
client/src/app/components/connection-status/connection-status.component.ts
client/src/app/components/header/header.component.html
client/src/app/components/shared.module.ts
client/src/app/components/user-state/user-state.component.html
client/src/app/components/user-state/user-state.component.scss
client/src/app/services/sync.service.ts
client/src/assets/i18n/en.json

Add ConnectionStatus-component + add Force-Offline override

---

client/_check-icons-in-use.js
client/angular.json
client/ngsw-config.json
client/package.json

Limit assets in build/prefetch for offline with automatic hard-coded list of icons

---

client/angular.json
client/package.json
client/src/app/components/header/header.component.html

fix: Use icon-name explicitly, to include in checks

---

README.md

Update README with seed data explanation

---

client/src/app/services/auth.service.ts

Add exception for mock-data/user in roles-check

---

client/angular.json
client/package-lock.json
client/package.json
client/src/app/app.module.ts
client/src/app/components/report-narrative/report-narrative.component.html
client/src/app/components/report-narrative/report-narrative.component.spec.ts
client/src/app/components/report-narrative/report-narrative.component.ts
client/src/app/components/report-section/report-section.component.html
client/src/app/components/shared.module.ts
client/src/app/mocks/program.mock.ts
client/src/app/models/question-data.model.ts
client/src/app/pages/report/report.page.html
client/src/app/pages/report/report.page.spec.ts
client/src/app/types/question-input.type.ts
client/src/assets/i18n/en.json
client/src/global.scss
server/src/seed-data/narrativeReportTemplate-demo-en.ts

- Add Markdown-rendering
- Optimize print-styling
- Add Print-button
Related #234

Enhance Report-page

---

client/src/app/components/question-section/question-section.component.html
client/src/app/components/shared.module.ts
client/src/app/directives/only-allowed-input.directive.spec.ts
client/src/app/directives/only-allowed-input.directive.ts

Rename directive to cover all uses

---

client/src/app/components/connection-status/connection-status.component.html
client/src/app/components/connection-status/connection-status.component.ts

Fix 'stickyness' of "offline"-state

---

client/src/app/components/nav-progress/nav-progress.component.html
client/src/app/components/nav-progress/nav-progress.component.ts
client/src/assets/i18n/en.json

Add section-pagination for individual sections

---

client/src/app/components/question-input/question-input.component.html
client/src/app/components/question-input/question-input.component.scss
client/src/app/components/question-input/question-input.component.spec.ts
client/src/app/components/question-input/question-input.component.ts
client/src/app/components/question-section/question-section.component.html
client/src/app/components/question-section/question-section.component.spec.ts
client/src/app/components/question-section/question-section.component.ts
client/src/app/components/shared.module.ts
client/src/global.scss

Extract QuestionInput-component from QuestionSection

---

client/src/app/services/notification.service.ts

fix: Prevent multiple notifications on top of each other

---

client/src/app/app.component.spec.ts
client/src/app/app.component.ts
client/src/app/components/question-input/question-input.component.html
client/src/app/components/question-input/question-input.component.scss
client/src/app/pages/program/program.page.html
client/src/app/services/notification.service.ts
client/src/app/services/program-data.service.ts
client/src/app/services/pub-sub.service.spec.ts
client/src/app/services/pub-sub.service.ts
client/src/app/services/state.service.ts
client/src/app/services/sync.service.spec.ts
client/src/app/services/sync.service.ts
client/src/app/types/question-input.type.ts
client/src/assets/i18n/en.json

+ PubSub-service refactorings
Related #397

Add state-indicator to question-input elements

---

README.md
client/.vscode/settings.json
client/src/app/components/login-form/login-form.component.html
client/src/app/components/question-input/question-input.component.html
client/src/app/home/home.module.ts
client/src/app/home/home.page.html
client/src/app/home/home.page.spec.ts
client/src/app/home/home.page.ts
client/src/app/pages/login/login.page.html
client/src/app/pages/login/login.page.spec.ts
client/src/app/services/notification.service.ts
client/src/app/services/translatable-string.service.spec.ts
client/src/assets/i18n/en.json
client/src/assets/i18n/nl.json
client/src/environments/environment.ts
client/src/global.scss
client/src/index.html
client/tsconfig.app.json

Add introduction/explanations to login-page (+translations cleanup)

---

README.md
server/src/scripts/seed-program.ts
server/src/seed-data/narrativeReportTemplate-demo-en.ts
server/src/seed-data/narrativeReportTemplate-test-en.ts

Add explanation + examples for the Narrative report

---

client/src/app/components/nav-progress/nav-progress.component.ts
client/src/app/components/report-narrative/report-narrative.component.html
client/src/app/components/report-narrative/report-narrative.component.scss
client/src/app/components/report-narrative/report-narrative.component.ts
client/src/app/helpers/answers.helpers.ts
client/src/app/services/program-data.service.ts
client/src/app/types/question-input.type.ts
client/src/assets/i18n/en.json
client/src/global.scss

Add a link to the Report/input-page on template-variables/placeholders

---

.github/workflows/main_CPDW-Staging.yml

Add manual deployment to Staging-environment

---

client/src/app/components/question-input/question-input.component.html
client/src/app/components/question-input/question-input.component.scss
client/src/app/components/question-input/question-input.component.ts
client/src/app/components/question-section/question-section.component.html

Add highlight-effect + scroll to question-links

---

client/src/app/components/report-narrative/report-narrative.component.html
client/src/app/components/report-narrative/report-narrative.component.ts

Reverts rodekruis/cash-program-design-wizard#452

Revert "WIP: Add quick-and-dirty Narrative-Report preview feature"

---

client/src/app/components/nav-progress/nav-progress.component.html
client/src/app/components/nav-progress/nav-progress.component.scss
client/src/app/components/question-input/question-input.component.scss
client/src/app/components/question-section/question-section.component.html
client/src/app/components/question-section/question-section.component.ts
client/src/app/mocks/program.mock.ts

Only show Comments on last-question-of-the-sub-section

---

client/src/app/pages/login/login.page.html
client/src/app/pages/login/login.page.ts
client/src/app/pages/program/program.page.html
client/src/app/pages/report/report.page.html
client/src/app/services/api.service.ts
client/src/app/services/notification.service.ts
client/src/global.scss
server/package.json
server/src/users/user.service.ts

Tweak layout + scroll behaviour for use on small(tablet) screens

---

server/package-lock.json
server/package.json

Align @types/node with Node.js version in use

---

client/src/app/components/question-section/question-section.component.html
client/src/assets/i18n/en.json

Change comment CTA + fix template logic

---

client/src/app/components/report-section/report-section.component.html

Show section-numbers in print

---

client/src/app/components/question-section/question-section.component.html
client/src/app/pages/program/program.page.html

Move section-label to (sticky) toolbar

---

client/src/app/components/question-input/question-input.component.html
client/src/app/components/question-input/question-input.component.spec.ts
client/src/app/components/question-input/question-input.component.ts
client/src/app/mocks/program.mock.ts
server/src/seed-data/questions-test.json
server/src/seed-data/subsections-test.json

Make links clickable (and questions 'stylable')

---

server/src/auth/roles-program.guard.ts
server/src/programs/dto/program.dto.ts
server/src/programs/programs.controller.ts
server/src/programs/programs.service.ts

Add endpoints to update Program properties

---

client/src/app/components/comment-input/comment-input.component.spec.ts
client/src/app/components/filters/filters.component.html
client/src/app/components/filters/filters.component.scss
client/src/app/components/question-input/question-input.component.spec.ts
client/src/app/components/question-section/question-section.component.ts
client/src/app/models/tag.enum.ts
client/src/app/pages/program/program.page.spec.ts
client/src/app/pages/report/report.page.spec.ts
client/src/app/services/state.service.spec.ts
client/src/assets/i18n/en.json
server/src/seed-data/questions.json

Change Tags + tweak layout/size of filter-component

---

server/src/seed-data/questions.json

Add "Returnee" option-choices + fix typo's etc.

---

client/src/app/components/comments-list/comments-list.component.html
client/src/app/components/nav-progress/nav-progress.component.html
client/src/app/components/report-narrative/report-narrative.component.html
client/src/assets/i18n/en.json

Use consistent date format + fix typo

---

client/src/app/pages/program/program.page.ts
client/src/app/pages/report/report.page.ts
client/src/app/services/state.service.ts

Refactor initialising of getting Program data

---

.github/workflows/main_CPDW-Development.yml
.github/workflows/main_CPDW-Staging.yml
.github/workflows/tests.yml

Upgrade GitHub Action setup-node to v3

---

client/src/app/components/comment-input/comment-input.component.spec.ts
client/src/app/components/program-phase/program-phase.component.html
client/src/app/components/question-input/question-input.component.spec.ts
client/src/app/models/tag.enum.ts
client/src/app/pages/program/program.page.html
client/src/app/pages/program/program.page.spec.ts
client/src/app/pages/report/report.page.spec.ts
client/src/app/services/state.service.spec.ts
client/src/assets/i18n/en.json
server/src/seed-data/questions-test.json
server/src/seed-data/questions.json

Change Phases into Tags

---

client/src/app/components/filters/filters.component.ts

Start tag-count from 0 every time

---

client/src/app/components/filters/filters.component.ts

Use 'manual' reset of tagCount

---

client/src/app/components/nav-progress/nav-progress.component.html

Keep selected filters active when switching (active)section

---

client/src/app/components/question-section/question-section.component.html
client/src/app/components/question-section/question-section.component.ts

Hide sub-sections completely when empty

---

client/src/app/components/filters/filters.component.html
client/src/app/components/filters/filters.component.ts
client/src/app/components/header/header.component.html
client/src/app/components/header/header.component.ts
client/src/app/components/question-input/question-input.component.html
client/src/app/components/question-input/question-input.component.scss
client/src/app/components/question-input/question-input.component.ts
client/src/app/pages/login/login.page.html
client/src/app/pages/manage-questions/manage-questions.page.html
client/src/app/pages/program/program.page.html
client/src/app/pages/report/report.page.html
client/src/assets/i18n/en.json
client/src/theme/variables.scss

feat: change tag buttons style

---

server/src/scripts/transfer-questions.ts

Fix import to allow for BOM-files (apparently)

---

client/src/app/components/question-input/question-input.component.html

Treat 'empty selection' as 'not answered'

---

server/src/scripts/seed-program.ts
server/src/scripts/transfer-questions.ts

Fix: OptionChoices get mis-ordered on import

---

server/src/scripts/transfer-questions.ts

Add specific sorting for predictable exports/imports
